precision = {
    "pH": 4,
    "pK": 4,
    "e1": 6,
    "e2": 6,
    "e3": 6,
    "Voltage": 3,
    "salinity": 2,
    "A1": 5,
    "A2": 5,
    "vol_injected": 2,
    "Anir": 2,
    "longitude": 6,
    "latitude": 6,
    "fb_temperature": 3,
    "pH_lab": 4,
    "T_cuvette": 3,
    "perturbation": 3,
    "evalAnir": 3,
    "pCO2": 4
}
